import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `msw init` — not our source.
    "public/mockServiceWorker.js",
    // Compiled output of the workspace packages. Linting emitted CommonJS
    // reports on tsc's `require()` calls, which is a rule about our source
    // being applied to a build artifact.
    "apps/*/dist/**",
    "packages/*/dist/**",
  ]),
]);

export default eslintConfig;
